### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by DJaeger** [JusticeRage/ApkTrack#83]
Since some time I get a SSL error for all requests throught the proxy.

```
12-15 08:56:59.015 V/ApkTrack(19393): Launching version check for Dolphin
12-15 08:56:59.015 V/ApkTrack(19393): Requesting https://apktrack.kwiatkowski.fr/version/mobi.mgeek.TunnyBrowser
12-15 08:56:59.205 E/ApkTrack(19393): https://apktrack.kwiatkowski.fr/version/mobi.mgeek.TunnyBrowser could not be retrieved! (SSL handshake aborted: ssl=0x79b03ca8: I/O error during system call, Connection reset by peer)
12-15 08:56:59.205 E/ApkTrack(19393): javax.net.ssl.SSLException: SSL handshake aborted: ssl=0x79b03ca8: I/O error during system call, Connection reset by peer
12-15 08:56:59.205 E/ApkTrack(19393):   at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
12-15 08:56:59.205 E/ApkTrack(19393):   at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:406)
12-15 08:56:59.205 E/ApkTrack(19393):   at com.android.okhttp.Connection.upgradeToTls(Connection.java:146)
12-15 08:56:59.205 E/ApkTrack(19393):   at com.android.okhttp.Connection.connect(Connection.java:107)
12-15 08:56:59.205 E/ApkTrack(19393):   at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:294)
12-15 08:56:59.205 E/ApkTrack(19393):   at com.android.okhttp.internal.http.HttpEngine.sendSocketRequest(HttpEngine.java:255)
12-15 08:56:59.205 E/ApkTrack(19393):   at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:206)
12-15 08:56:59.205 E/ApkTrack(19393):   at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:345)
12-15 08:56:59.205 E/ApkTrack(19393):   at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:89)
12-15 08:56:59.205 E/ApkTrack(19393):   at com.android.okhttp.internal.http.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:161)
12-15 08:56:59.205 E/ApkTrack(19393):   at fr.kwiatkowski.apktrack.service.WebService.get_page(WebService.java:152)
12-15 08:56:59.205 E/ApkTrack(19393):   at fr.kwiatkowski.apktrack.service.WebService._perform_version_check(WebService.java:453)
12-15 08:56:59.205 E/ApkTrack(19393):   at fr.kwiatkowski.apktrack.service.WebService.onHandleIntent(WebService.java:107)
12-15 08:56:59.205 E/ApkTrack(19393):   at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
12-15 08:56:59.205 E/ApkTrack(19393):   at android.os.Handler.dispatchMessage(Handler.java:102)
12-15 08:56:59.205 E/ApkTrack(19393):   at android.os.Looper.loop(Looper.java:136)
12-15 08:56:59.205 E/ApkTrack(19393):   at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by JusticeRage** [comment]
Thanks for letting me know. I had updated the web server's configuration to use more recent SSL algorithms. Mayve in the process, some devices ceased to be able to establish a secure connexion (because there are no longer algorithms in common).

I've downgraded the configuration so that "old" SSL clients are supported again, let me know if this was the issue.

**Comment by DJaeger** [comment]
Still the same issue

**Comment by JusticeRage** [comment]
Wow, I'm drawing a blank here.
Does this error happen all the time, or sporadically? When did this begin? What device (and OS version) are you using?
Is anyone else facing this issue?

**Comment by ThibaultMndr** [comment]
I'm facing the same issue, approximatively since one month. Using F-Droid, PlayStore or X-Posed works, but AppBrain/ApkTrackStable does not.

Ainol Spark, Cyanogenmod 11 unofficial build of summer 2014, not upgradable, so I suspect an openssl unsupported cipher issue

**Comment by JusticeRage** [comment]
I've tinkered with my server's nginx configuration some more, and [SSLLabs](https://www.ssllabs.com/ssltest/analyze.html?d=apktrack.kwiatkowski.fr&hideResults=on) reports that all recent Android versions should be supported. Apologies for the inconvenience, and thanks for reporting the problem.

I should add that the proxy is not receiving version information from AppBrain since yesterday (they return blank pages). The situation is currently being resolved, but it may take a few more days before the proxy works properly.

**Comment by ThibaultMndr** [comment]
Thanks a lot it works for me now.
